// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/deploy.proto

package deploypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployEvent_Level int32

const (
	DeployEvent_LEVEL_UNSPECIFIED DeployEvent_Level = 0
	DeployEvent_LEVEL_INFO        DeployEvent_Level = 1
	DeployEvent_LEVEL_SUCCESS     DeployEvent_Level = 2
	DeployEvent_LEVEL_ERROR       DeployEvent_Level = 3
)

// Enum value maps for DeployEvent_Level.
var (
	DeployEvent_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_INFO",
		2: "LEVEL_SUCCESS",
		3: "LEVEL_ERROR",
	}
	DeployEvent_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_INFO":        1,
		"LEVEL_SUCCESS":     2,
		"LEVEL_ERROR":       3,
	}
)

func (x DeployEvent_Level) Enum() *DeployEvent_Level {
	p := new(DeployEvent_Level)
	*p = x
	return p
}

func (x DeployEvent_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployEvent_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_deploy_proto_enumTypes[0].Descriptor()
}

func (DeployEvent_Level) Type() protoreflect.EnumType {
	return &file_api_proto_deploy_proto_enumTypes[0]
}

func (x DeployEvent_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployEvent_Level.Descriptor instead.
func (DeployEvent_Level) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_deploy_proto_rawDescGZIP(), []int{2, 0}
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ImageName     string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	AppType       string                 `protobuf:"bytes,6,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,7,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_api_proto_deploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *DeployRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeployRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *DeployRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DeployRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DeployRequest) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *DeployRequest) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type BootstrapRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ImageName     string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	AppType       string                 `protobuf:"bytes,6,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,7,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRepositoryRequest) Reset() {
	*x = BootstrapRepositoryRequest{}
	mi := &file_api_proto_deploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRepositoryRequest) ProtoMessage() {}

func (x *BootstrapRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRepositoryRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapRepositoryRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *BootstrapRepositoryRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *BootstrapRepositoryRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *BootstrapRepositoryRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BootstrapRepositoryRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BootstrapRepositoryRequest) GetAppType() string {
	if x != nil {
		return x.AppType
	}
	return ""
}

func (x *BootstrapRepositoryRequest) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type DeployEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         DeployEvent_Level      `protobuf:"varint,1,opt,name=level,proto3,enum=deploy.v1.DeployEvent_Level" json:"level,omitempty"`
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ImageName     string                 `protobuf:"bytes,4,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Domain        string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployEvent) Reset() {
	*x = DeployEvent{}
	mi := &file_api_proto_deploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployEvent) ProtoMessage() {}

func (x *DeployEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployEvent.ProtoReflect.Descriptor instead.
func (*DeployEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *DeployEvent) GetLevel() DeployEvent_Level {
	if x != nil {
		return x.Level
	}
	return DeployEvent_LEVEL_UNSPECIFIED
}

func (x *DeployEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DeployEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeployEvent) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *DeployEvent) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *DeployEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_api_proto_deploy_proto protoreflect.FileDescriptor

const file_api_proto_deploy_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/deploy.proto\x12\tdeploy.v1\"\xda\x01\n" +
	"\rDeployRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x19\n" +
	"\bapp_type\x18\x06 \x01(\tR\aappType\x12!\n" +
	"\fnode_version\x18\a \x01(\tR\vnodeVersion\"\xe7\x01\n" +
	"\x1aBootstrapRepositoryRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x19\n" +
	"\bapp_type\x18\x06 \x01(\tR\aappType\x12!\n" +
	"\fnode_version\x18\a \x01(\tR\vnodeVersion\"\xa3\x02\n" +
	"\vDeployEvent\x122\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1c.deploy.v1.DeployEvent.LevelR\x05level\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"image_name\x18\x04 \x01(\tR\timageName\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\"R\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x01\x12\x11\n" +
	"\rLEVEL_SUCCESS\x10\x02\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x032\xa5\x01\n" +
	"\rDeployService\x12<\n" +
	"\x06Deploy\x12\x18.deploy.v1.DeployRequest\x1a\x16.deploy.v1.DeployEvent0\x01\x12V\n" +
	"\x13BootstrapRepository\x12%.deploy.v1.BootstrapRepositoryRequest\x1a\x16.deploy.v1.DeployEvent0\x01B&Z$deploy-service/pkg/deploypb;deploypbb\x06proto3"

var (
	file_api_proto_deploy_proto_rawDescOnce sync.Once
	file_api_proto_deploy_proto_rawDescData []byte
)

func file_api_proto_deploy_proto_rawDescGZIP() []byte {
	file_api_proto_deploy_proto_rawDescOnce.Do(func() {
		file_api_proto_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_deploy_proto_rawDesc), len(file_api_proto_deploy_proto_rawDesc)))
	})
	return file_api_proto_deploy_proto_rawDescData
}

var file_api_proto_deploy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_deploy_proto_goTypes = []any{
	(DeployEvent_Level)(0),             // 0: deploy.v1.DeployEvent.Level
	(*DeployRequest)(nil),              // 1: deploy.v1.DeployRequest
	(*BootstrapRepositoryRequest)(nil), // 2: deploy.v1.BootstrapRepositoryRequest
	(*DeployEvent)(nil),                // 3: deploy.v1.DeployEvent
}
var file_api_proto_deploy_proto_depIdxs = []int32{
	0, // 0: deploy.v1.DeployEvent.level:type_name -> deploy.v1.DeployEvent.Level
	1, // 1: deploy.v1.DeployService.Deploy:input_type -> deploy.v1.DeployRequest
	2, // 2: deploy.v1.DeployService.BootstrapRepository:input_type -> deploy.v1.BootstrapRepositoryRequest
	3, // 3: deploy.v1.DeployService.Deploy:output_type -> deploy.v1.DeployEvent
	3, // 4: deploy.v1.DeployService.BootstrapRepository:output_type -> deploy.v1.DeployEvent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_deploy_proto_init() }
func file_api_proto_deploy_proto_init() {
	if File_api_proto_deploy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_deploy_proto_rawDesc), len(file_api_proto_deploy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_deploy_proto_goTypes,
		DependencyIndexes: file_api_proto_deploy_proto_depIdxs,
		EnumInfos:         file_api_proto_deploy_proto_enumTypes,
		MessageInfos:      file_api_proto_deploy_proto_msgTypes,
	}.Build()
	File_api_proto_deploy_proto = out.File
	file_api_proto_deploy_proto_goTypes = nil
	file_api_proto_deploy_proto_depIdxs = nil
}
