// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: deploy.proto

package deploypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeployService_Deploy_FullMethodName              = "/deploy.v1.DeployService/Deploy"
	DeployService_BootstrapRepository_FullMethodName = "/deploy.v1.DeployService/BootstrapRepository"
	DeployService_Undeploy_FullMethodName            = "/deploy.v1.DeployService/Undeploy"
)

// DeployServiceClient is the client API for DeployService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployServiceClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployEvent], error)
	BootstrapRepository(ctx context.Context, in *BootstrapRepositoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployEvent], error)
	Undeploy(ctx context.Context, in *UndeployRequest, opts ...grpc.CallOption) (*UndeployResponse, error)
}

type deployServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployServiceClient(cc grpc.ClientConnInterface) DeployServiceClient {
	return &deployServiceClient{cc}
}

func (c *deployServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeployService_ServiceDesc.Streams[0], DeployService_Deploy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeployRequest, DeployEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployService_DeployClient = grpc.ServerStreamingClient[DeployEvent]

func (c *deployServiceClient) BootstrapRepository(ctx context.Context, in *BootstrapRepositoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeployEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeployService_ServiceDesc.Streams[1], DeployService_BootstrapRepository_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BootstrapRepositoryRequest, DeployEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployService_BootstrapRepositoryClient = grpc.ServerStreamingClient[DeployEvent]

func (c *deployServiceClient) Undeploy(ctx context.Context, in *UndeployRequest, opts ...grpc.CallOption) (*UndeployResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeployResponse)
	err := c.cc.Invoke(ctx, DeployService_Undeploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServiceServer is the server API for DeployService service.
// All implementations must embed UnimplementedDeployServiceServer
// for forward compatibility.
type DeployServiceServer interface {
	Deploy(*DeployRequest, grpc.ServerStreamingServer[DeployEvent]) error
	BootstrapRepository(*BootstrapRepositoryRequest, grpc.ServerStreamingServer[DeployEvent]) error
	Undeploy(context.Context, *UndeployRequest) (*UndeployResponse, error)
	mustEmbedUnimplementedDeployServiceServer()
}

// UnimplementedDeployServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployServiceServer struct{}

func (UnimplementedDeployServiceServer) Deploy(*DeployRequest, grpc.ServerStreamingServer[DeployEvent]) error {
	return status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedDeployServiceServer) BootstrapRepository(*BootstrapRepositoryRequest, grpc.ServerStreamingServer[DeployEvent]) error {
	return status.Error(codes.Unimplemented, "method BootstrapRepository not implemented")
}
func (UnimplementedDeployServiceServer) Undeploy(context.Context, *UndeployRequest) (*UndeployResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Undeploy not implemented")
}
func (UnimplementedDeployServiceServer) mustEmbedUnimplementedDeployServiceServer() {}
func (UnimplementedDeployServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeployServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployServiceServer will
// result in compilation errors.
type UnsafeDeployServiceServer interface {
	mustEmbedUnimplementedDeployServiceServer()
}

func RegisterDeployServiceServer(s grpc.ServiceRegistrar, srv DeployServiceServer) {
	// If the following call panics, it indicates UnimplementedDeployServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeployService_ServiceDesc, srv)
}

func _DeployService_Deploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServiceServer).Deploy(m, &grpc.GenericServerStream[DeployRequest, DeployEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployService_DeployServer = grpc.ServerStreamingServer[DeployEvent]

func _DeployService_BootstrapRepository_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BootstrapRepositoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServiceServer).BootstrapRepository(m, &grpc.GenericServerStream[BootstrapRepositoryRequest, DeployEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployService_BootstrapRepositoryServer = grpc.ServerStreamingServer[DeployEvent]

func _DeployService_Undeploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServiceServer).Undeploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployService_Undeploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServiceServer).Undeploy(ctx, req.(*UndeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployService_ServiceDesc is the grpc.ServiceDesc for DeployService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deploy.v1.DeployService",
	HandlerType: (*DeployServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Undeploy",
			Handler:    _DeployService_Undeploy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deploy",
			Handler:       _DeployService_Deploy_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BootstrapRepository",
			Handler:       _DeployService_BootstrapRepository_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deploy.proto",
}
